Actual/main/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name = 'home'),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path('login', views.Login.as_view(), name = 'login'),
    path('logout', views.logout_user, name = 'logout'),
    path('faq', views.faq, name = 'faq'),
    path('communication', views.communication, name = 'communication'),
    path('about', views.about, name = 'about'),
    path('catalog', include('shop.urls',  namespace = 'shop'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Actual/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path("create/", views.create),
    path('zakaz', views.zakaz, name='zakaz'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail')
]

Actual/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog', include('shop.urls',  namespace = 'shop'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Actual/shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    """Категории, к которым относятся товары"""
    name = models.CharField(max_length=150, db_index=True, verbose_name='Название категории')
    slug = models.SlugField(max_length=150, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    """Модель описания продукта"""
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE,
                                 verbose_name='Выберите категорию'
                                 )
    name = models.CharField(max_length=200, db_index=True, verbose_name='Наменование')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Фото')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_detail', args=[self.id, self.slug])
    

class Zakaz(models.Model):
    name = models.CharField(max_length=35,verbose_name='Имя')
    number = models.BigIntegerField(verbose_name='Телефон')   

    class Meta:
        ordering = ('name',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

Actual/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView

class SignUp(CreateView):
    form_class = UserCreationForm
    template_name = "main/registration.html"

    def get_success_url(self):
        return reverse_lazy('home')


class Login(LoginView):
    form_class = AuthenticationForm
    template_name = "main/login.html"

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return redirect('login')

def index(request):
    return render(request, 'main/index.html')


def registration(request):
    return render(request, 'main/registration.html')


def faq(request):
    return render(request, 'main/faq.html')


def communication(request):
    return render(request, 'main/communication.html')


def about(request):
    return render(request, 'main/about.html')

def login(request):
    return render(request, 'main/login.html')

Actual/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Category, Product, Zakaz

def product_list(request, category_slug=None):
    """" Страница списка товаров"""
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {'category': category, 'categories': categories, 'products': products}
    return render(request, 'shop/list.html', context)


def product_detail(request, id, slug):
    """ Страница продукта"""
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    context = {'product': product}
    return render(request, 'shop/detail.html', context)

def zakaz(request):
    return render(request, 'shop/zakaz.html')


def create(request):
    if request.method == "POST":
        person = Zakaz()
        person.name = request.POST.get("name")
        person.number = request.POST.get("number")
        person.save()
    return HttpResponseRedirect("/")

Actual/main/templates/main/about.html
{% extends 'main/layout.html' %}
{% block reg %}
{% endblock %}

{% block content %}
<div class="container">
    <p>«ElectrIIC»;– одна из крупнейших сетей магазинов электроники и бытовой техники, входит в ГК Merlion. На рынке с 2008 года.</p>
    <p>В инфраструктуре компании интернет-магазин, более 855 магазинов и пунктов выдачи заказов в 372 городах России.</p>
    <p>В продуктовом портфеле порядка 800 мировых брендов и 70000 наименований компьютерной, цифровой, бытовой техники, других категорий товаров, включая садовую, автомобильную электронику, офисную мебель, канцелярию.</p>
    <p>В портфеле услуг – сборка компьютеров, установка техники, подборка расходных материалов, электронные ключи и подписи, защита покупки и имущества, а также иные цифровые услуги.</p>
    <p>Магазины «ElectrIIC» оборудованы терминалами для самостоятельного оформления заказов, кассами оплаты и окнами выдачи товаров. Сall-центр компании работает 7 дней в неделю и оказывает круглосуточную поддержку покупателям.</p>
    <p>Количество визитов в месяц— более 35 миллионов человек;</p>
    <p style="margin:0cm;margin-bottom:.0001pt;text-align:justify;background:white">&nbsp;</p>
    <p><strong>«ElectrIIC» занимает лидирующие позиции на рынке&nbsp;электронной торговли:</strong></p>
    <p>В 2015 году -&nbsp;2-ое место в рейтинге журнала Forbes «TOP-20 онлайн-магазинов России».</p>
    <p>В 2015 году -&nbsp;4-ое место в рейтинге журнала Forbes «20 самых дорогих компаний Рунета».</p>
    <p>В 2016 году -&nbsp;8-ое место в рейтинге журнала Forbes «20 самых дорогих компаний Рунета».</p>
    <p>В 2016 году -&nbsp;3-е место по объему онлайн-продаж в рейтинге Data Insight и Ruward E-commerce Index TOP-100.</p>
    <p>В 2017 году -&nbsp;2-е место по объему онлайн-продаж в рейтинге Data Insight и Ruward E-commerce Index TOP-100.</p>
    <p>В 2019 году -&nbsp;1-е место в исследовании Data Insight «Онлайн-рынок бытовой техники и электроники» (период: июль 2018-июнь 2019).</p>
    <p>В 2019 году&nbsp;— 7-е место в рейтинге «20 самых дорогих компаний Рунета» по версии Forbes. Единственный онлайн-ретейлер в рейтинге, который специализируется на торговле электроникой и бытовой техникой.</p>
    <p>В 2020 году – 2-е место в рейтинге Data Insight TOP-100 крупнейших магазинов России E-Commerce Index.</p>
    <p>В 2020 году – &nbsp;8-е место в рейтинге Forbes «10 главных продавцов Рунета».</p>
    <p>В 2012, 2013, 2014, 2015, 2016, 2018, 2019 годах «ElectrIIC» удостоен звания «Привлекательный работодатель» по итогам исследования портала Superjob.ru среди работающих в России компаний.&nbsp;</p>         
</div>                     
{% endblock %}

Actual/main/templates/main/communication.html
{% extends 'main/layout.html' %}
{% block reg %}
{% endblock %}

{% block content %}
<div class="container"><h4><b>Информация о продавце:</b></h4><p>Наименование: Общество с ограниченной ответственностью «ElectrIIC»<br>
    Юридический адрес: 420111, г.&nbsp;Казань, Кремлёвская улица, д.&nbsp;35, стр.&nbsp;1, этаж&nbsp;1, пом.&nbsp;I, ком.&nbsp;51 ОГРН: 1147746461422</p>
    <p>Уважаемые покупатели!</p>
    <p>Мы всегда готовы Вам помочь и оказать необходимую помощь.</p>
    <p>Если, к нашему сожалению, у Вас возникли претензии, связанные с приобретенными у нас товарами либо с процессом их приобретения, просим направлять претензии в письменной форме по адресу: 420111, г. Казань, Кремлёвская улица, д. 35, стр. 1, этаж 1, пом. I, ком. 51.</p>
    <p>Обращения, направленные в иной форме и (или) иным способом, не признаются официальными претензиями в силу пунктов 19 и 21 Правил продажи товаров по договору розничной купли-продажи, утвержденных Постановлением Правительства РФ от 31.12.2020 №&nbsp;2463, а ответы на такие обращения не признаются юридически значимыми.</p>
    <p>Данные ограничения продиктованы желанием неукоснительного соблюдения Ваших прав и законных интересов.</p>
    <iframe src="https://yandex.ru/map-widget/v1/-/CCUceCvIGB" width="100%" height="350" frameborder="1" allowfullscreen="true"></iframe>
</div>

{% endblock %}

Actual/main/templates/main/index.html
{% extends 'main/layout.html' %}

{% load static %}

{% block reg %}
<div class="col-md-3">
    {% if request.user.is_authenticated %}
    <div class="login-register">
        {{ user.username }}
      <a href="{% url 'logout' %}" class="btn btn-outline-secondary" id="button-login">Выйти</a>
    </div>
    {% else %}
    <div class="login-register">
        <a href="{% url 'login' %}" class="btn btn-outline-secondary" id="button-login">Войти</a>
        <a href="{% url 'signup' %}" class="btn btn-primary">Зарегистрироваться</a>
      </div>
    {% endif %}
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="popular-categories">Популярные категории</div>
    <div class="row">
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/note.png' %}" alt="Ноутбуки">
            </button>
        </div>
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/LE24B8000T_m.png' %}" alt="Телевизоры">
            </button>
        </div>
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/telephones_250x200_210.png' %}" alt="Смартфоны">
            </button>
        </div>
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/Chto-takoe-konfigura-200x200h.png' %}" alt="Компьютеры">
            </button>
        </div>
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/16KG-200x200.png' %}" alt="Стиральные машины">
            </button>
        </div>
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/52406-1-refrigerator-png-download-free-thumb.png' %}" alt="Холодильники">
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/note.png' %}" alt="Ноутбуки">
            </button>
        </div>
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/LE24B8000T_m.png' %}" alt="Телевизоры">
            </button>
        </div>
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/telephones_250x200_210.png' %}" alt="Смартфоны">
            </button>
        </div>
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/Chto-takoe-konfigura-200x200h.png' %}" alt="Компьютеры">
            </button>
        </div>
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/16KG-200x200.png' %}" alt="Стиральные машины">
            </button>
        </div>
        <div class="col-md-2">
            <button class="btn btn-primary btn-big">
                <img src="{% static 'main/Pictures/52406-1-refrigerator-png-download-free-thumb.png' %}" alt="Холодильники">
            </button>
        </div>
    </div>
</div>
{% endblock %}

Actual/main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ElectricIIC</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css">
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-element-bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body>
    <header>
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-3">
              <div class="logo">
                <a href="{% url 'home' %}"><img src="{% static 'main/Pictures/Logo.png' %}" alt="Logo"></a>
              </div>
              <div class="category">
                <a class="btn btn-primary" href="catalog" role="button">Каталог</a>
              </div>
            </div>
            <div class="col-md-6">
              <swiper-container class="mySwiper" navigation="true" pagination="true" keyboard="true" mousewheel="true"
              css-mode="true">
              <swiper-slide><img src="{% static 'main/Pictures/15_600.jpg' %}" alt=""></swiper-slide>
              <swiper-slide><img src="{% static 'main/Pictures/a04b396ec281938cfbd465c486a18369.jpg' %}" alt=""></swiper-slide>
              <swiper-slide><img src="{% static 'main/Pictures/Banner-1_bfb77_.png' %}" alt=""></swiper-slide>
            </swiper-container>
            </div>
            {% block reg %}
            {% endblock %}
          </div>
        </div>
        {% block content %}
        {% endblock %}
        <div class="container3">
            <footer class="py-3 my-4">
              <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="{% url 'home' %}" class="nav-link px-2 text-body-secondary">Начальная страница</a></li>
                <li class="nav-item"><a href="{% url 'communication' %}" class="nav-link px-2 text-body-secondary">Обратная связь</a></li>
                <li class="nav-item"><a href="{% url 'faq' %}" class="nav-link px-2 text-body-secondary">FAQ</a></li>
                <li class="nav-item"><a href="{% url 'about' %}" class="nav-link px-2 text-body-secondary">О нас</a></li>
              </ul>
              <p class="text-center text-body-secondary">© 2023 ElectricIIC</p>
            </footer>
        </div>
            
    </header>
</body>
</html>

Actual/main/templates/main/login.html
{% extends 'main/layout.html' %}
{% block reg %}
{% endblock %}
{% block content %}
<div class="container">
    <form method="post">
      {% csrf_token %}
      <table>
        {{ form.as_p }}
        <tr>
          <td>&nbsp;</td>
          <td><input type="submit" value="Submit"></td>
        </tr>                
      </table>
    </form>
</div>
{% endblock %}

Actual/main/templates/main/registration.html
{% extends 'main/layout.html' %}
{% block reg %}
{% endblock %}
{% block content %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Register">
</form>
</form>
</div>
{% endblock %}

Actual/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ElectricIIC</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css">
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-element-bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body>
<div id="header">
    <div class="container">
        <div class="row align-items-center">
          <div class="col-md-3">
            <div class="logo">
              <a href="{% url 'home' %}"><img src="{% static 'main/Pictures/Logo.png' %}" alt="Logo"></a>
            </div>
            <div class="category">
              <a class="btn btn-primary" href="{% url 'home' %}" role="button">Сделать заказ</a>
            </div>
          </div>
          <div class="col-md-6">
            <swiper-container class="mySwiper" navigation="true" pagination="true" keyboard="true" mousewheel="true"
            css-mode="true">
            <swiper-slide><img src="{% static 'main/Pictures/15_600.jpg' %}" alt=""></swiper-slide>
            <swiper-slide><img src="{% static 'main/Pictures/a04b396ec281938cfbd465c486a18369.jpg' %}" alt=""></swiper-slide>
            <swiper-slide><img src="{% static 'main/Pictures/Banner-1_bfb77_.png' %}" alt=""></swiper-slide>
          </swiper-container>
          </div>
          {% block reg %}
          <div class="col-md-3">
            {% if request.user.is_authenticated %}

            <div class="login-register">
                {{ user.username }}
              <a href="{% url 'logout' %}" class="btn btn-outline-secondary" id="button-login">Выйти</a>
            </div>
            {% else %}
            <div class="login-register">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary" id="button-login">Войти</a>
                <a href="{% url 'signup' %}" class="btn btn-primary">Зарегистрироваться</a>
              </div>
            {% endif %}
        </div>
          {% endblock %}
        </div>
      </div>
</div>
<div id="content">
{% block content %}{% endblock %}
</div>
<div class="container3">
    <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="{% url 'home' %}" class="nav-link px-2 text-body-secondary">Начальная страница</a></li>
        <li class="nav-item"><a href="{% url 'communication' %}" class="nav-link px-2 text-body-secondary">Обратная связь</a></li>
        <li class="nav-item"><a href="{% url 'faq' %}" class="nav-link px-2 text-body-secondary">FAQ</a></li>
        <li class="nav-item"><a href="{% url 'about' %}" class="nav-link px-2 text-body-secondary">О нас</a></li>
      </ul>
      <p class="text-center text-body-secondary">© 2023 ElectricIIC</p>
    </footer>
</div>
</body>
</html>

Actual/shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
<h1>{{ product.name }}</h1>
<h2>
<a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
</h2>
<p class="price">${{ product.price }}</p>
{{ product.description|linebreaks }}
</div>
{% endblock %}

Actual/shop/templates/shop/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
<h3>Категория</h3>
<ul>
<li {% if not category %}class="selected"{% endif %}>
<a href="{% url 'shop:product_list' %}">Все</a>
</li>
{% for c in categories %}
<li {% if category.slug == c.slug %}class="selected" {% endif %}>
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
{% endfor %}
</ul>
</div>
<div id="main" class="product-list">
<h1>{% if category %}{{ category.name }}{% else %}Товар{% endif %}</h1>
{% for product in products %}
<div class="item">
<a href="{{ product.get_absolute_url }}">
    <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}">
</a>
<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
<br>
${{ product.price }}
</div>
{% endfor %}
</div>
{% endblock %}

Actual/shop/templates/shop/zakaz.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% endblock %}
{% block content %}
<div class="container">
    <p>Для заказа необходимо заполнить форму, вам перезвонят в ближайшее время</p>
<form method="POST" action="create/">
    {% csrf_token %}
    <p>
        <label>Введите имя</label><br>
        <input type="text" name="name" />
    </p>
    <p>
        <label>Введите номер</label><br>
        <input type="number" name="number" />
    </p>
    <input type="submit" value="Отправить" >
</form>
</div>
{% endblock %}